### PR TITLE
rename files and create folder structure

### PR DESCRIPTION
**Pull request by pedroheyerdahl-upwork**

### CODE REVIEW

**Review by giovanibrmiguel — COMMENTED** [review]
What's the purpose of the empty "talent_scout" file inside marts folder? Why it doesn't have an extension?

Was it supposed to be a folder instead? In this case maybe we should also create a folder for AnyHire. :)

**Comment by pedroheyerdahl-upwork** [comment]
talent_scout was supposed to be an empty folder for demo purposes. new commit fixed that and renamed sources.yml per our last discussion. thank you for the callout

**Comment by pedroheyerdahl-upwork** [comment]
Sources and references are now up to date. The project compiles successfully and docs are generated as expected. `dbt run` is able to write to the dev target schema, but code needs to be fixed/migrated to Databricks syntax.

**Review by giovanibrmiguel — APPROVED** [review]
LGTM!

**Pull request merged**
